const COMPARISON_DATA = [
  {
    "id": "sichuan_鞋子",
    "key": "sichuan",
    "name": "四川话 (Sichuanese)",
    "lat": 30.57,
    "lng": 104.06,
    "scene": "鞋子",
    "text_std": "我的鞋子去哪里了？",
    "text_dia": "我的孩儿跑哪切了？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_鞋子/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_鞋子/02_input_dialect.wav"
  },
  {
    "id": "tianjin_询问物品",
    "key": "tianjin",
    "name": "天津话 (Tianjin)",
    "lat": 39.08,
    "lng": 117.2,
    "scene": "询问物品",
    "text_std": "这是什么东西？",
    "text_dia": "介似嘛玩意儿？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/tianjin_询问物品/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/tianjin_询问物品/02_input_dialect.wav"
  },
  {
    "id": "shanghai_询问人物",
    "key": "shanghai",
    "name": "上海话 (Shanghainese)",
    "lat": 31.23,
    "lng": 121.47,
    "scene": "询问人物",
    "text_std": "他是你的朋友吗？",
    "text_dia": "伊是侬个朋友伐？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shanghai_询问人物/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shanghai_询问人物/02_input_dialect.wav"
  },
  {
    "id": "hunan_否定状态",
    "key": "hunan",
    "name": "湖南话 (Xiang)",
    "lat": 28.22,
    "lng": 112.93,
    "scene": "否定状态",
    "text_std": "我没有吃饭。",
    "text_dia": "我冒吃饭。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/hunan_否定状态/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/hunan_否定状态/02_input_dialect.wav"
  },
  {
    "id": "minnan_问候吃饭",
    "key": "minnan",
    "name": "闽南话 (Min Nan)",
    "lat": 24.47,
    "lng": 118.08,
    "scene": "问候吃饭",
    "text_std": "你吃了吗？",
    "text_dia": "汝食未？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/minnan_问候吃饭/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/minnan_问候吃饭/02_input_dialect.wav"
  },
  {
    "id": "dongbei_强调心情",
    "key": "dongbei",
    "name": "东北话 (Northeastern)",
    "lat": 41.8,
    "lng": 123.43,
    "scene": "强调心情",
    "text_std": "他今天心情特别不好，很郁闷。",
    "text_dia": "他今儿个心里老憋屈了，贼闹心。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/dongbei_强调心情/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/dongbei_强调心情/02_input_dialect.wav"
  },
  {
    "id": "cantonese_所有格与存在",
    "key": "cantonese",
    "name": "广东话 (Cantonese)",
    "lat": 23.12,
    "lng": 113.26,
    "scene": "所有格与存在",
    "text_std": "这是我的书，不是他的。",
    "text_dia": "呢本系我嘅书，唔系佢嘅。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/cantonese_所有格与存在/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/cantonese_所有格与存在/02_input_dialect.wav"
  },
  {
    "id": "shanghai_称呼",
    "key": "shanghai",
    "name": "上海话 (Shanghainese)",
    "lat": 31.23,
    "lng": 121.47,
    "scene": "称呼",
    "text_std": "他是你的朋友吗？",
    "text_dia": "伊是侬个朋友伐？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shanghai_称呼/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shanghai_称呼/02_input_dialect.wav"
  },
  {
    "id": "cantonese_询问人物与动作",
    "key": "cantonese",
    "name": "广东话 (Cantonese)",
    "lat": 23.12,
    "lng": 113.26,
    "scene": "询问人物与动作",
    "text_std": "那个人是谁？在看什么？",
    "text_dia": "嗰个人系边个？喺度睇咩啊？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/cantonese_询问人物与动作/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/cantonese_询问人物与动作/02_input_dialect.wav"
  },
  {
    "id": "hunan_询问动作",
    "key": "hunan",
    "name": "湖南话 (Xiang)",
    "lat": 28.22,
    "lng": 112.93,
    "scene": "询问动作",
    "text_std": "你在干什么呢？",
    "text_dia": "你在搞么子啰？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/hunan_询问动作/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/hunan_询问动作/02_input_dialect.wav"
  },
  {
    "id": "sichuan_日常疑问",
    "key": "sichuan",
    "name": "四川话 (Sichuanese)",
    "lat": 30.57,
    "lng": 104.06,
    "scene": "日常疑问",
    "text_std": "你在做什么？",
    "text_dia": "你在搞啥子？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_日常疑问/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_日常疑问/02_input_dialect.wav"
  },
  {
    "id": "cantonese_表达喜好",
    "key": "cantonese",
    "name": "广东话 (Cantonese)",
    "lat": 23.12,
    "lng": 113.26,
    "scene": "表达喜好",
    "text_std": "我很喜欢吃这个。",
    "text_dia": "我好钟意食呢个。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/cantonese_表达喜好/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/cantonese_表达喜好/02_input_dialect.wav"
  },
  {
    "id": "minnan_自己人",
    "key": "minnan",
    "name": "闽南话 (Min Nan)",
    "lat": 24.47,
    "lng": 118.08,
    "scene": "自己人",
    "text_std": "不用客气，都是自己人。",
    "text_dia": "免客气，拢是胶己人。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/minnan_自己人/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/minnan_自己人/02_input_dialect.wav"
  },
  {
    "id": "shanghai_问候与吃饭",
    "key": "shanghai",
    "name": "上海话 (Shanghainese)",
    "lat": 31.23,
    "lng": 121.47,
    "scene": "问候与吃饭",
    "text_std": "你好，你吃饭了吗？",
    "text_dia": "侬好，侬饭吃过伐？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shanghai_问候与吃饭/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shanghai_问候与吃饭/02_input_dialect.wav"
  },
  {
    "id": "tianjin_指责胡说",
    "key": "tianjin",
    "name": "天津话 (Tianjin)",
    "lat": 39.08,
    "lng": 117.2,
    "scene": "指责胡说",
    "text_std": "你不要胡说八道。",
    "text_dia": "你少在这儿胡诌瞎掰。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/tianjin_指责胡说/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/tianjin_指责胡说/02_input_dialect.wav"
  },
  {
    "id": "sichuan_不知道",
    "key": "sichuan",
    "name": "四川话 (Sichuanese)",
    "lat": 30.57,
    "lng": 104.06,
    "scene": "不知道",
    "text_std": "我不知道这件事情。",
    "text_dia": "我晓都不得这个事。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_不知道/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_不知道/02_input_dialect.wav"
  },
  {
    "id": "shanghai_询问事物",
    "key": "shanghai",
    "name": "上海话 (Shanghainese)",
    "lat": 31.23,
    "lng": 121.47,
    "scene": "询问事物",
    "text_std": "你在说什么东西？",
    "text_dia": "侬勒讲点啥个物事？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shanghai_询问事物/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shanghai_询问事物/02_input_dialect.wav"
  },
  {
    "id": "sichuan_强调语气",
    "key": "sichuan",
    "name": "四川话 (Sichuanese)",
    "lat": 30.57,
    "lng": 104.06,
    "scene": "强调语气",
    "text_std": "你不必担心，肯定没问题的。",
    "text_dia": "你莫操心嘛，肯定要得噻。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_强调语气/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_强调语气/02_input_dialect.wav"
  },
  {
    "id": "dongbei_身体部位",
    "key": "dongbei",
    "name": "东北话 (Northeastern)",
    "lat": 41.8,
    "lng": 123.43,
    "scene": "身体部位",
    "text_std": "我的膝盖被撞得有点疼。",
    "text_dia": "俺波棱盖儿卡得生疼。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/dongbei_身体部位/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/dongbei_身体部位/02_input_dialect.wav"
  },
  {
    "id": "shan3xi_询问动作",
    "key": "shan3xi",
    "name": "陕西话 (Shaanxi)",
    "lat": 34.34,
    "lng": 108.93,
    "scene": "询问动作",
    "text_std": "你在这里干什么？",
    "text_dia": "你在这达弄啥呢嘛？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shan3xi_询问动作/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shan3xi_询问动作/02_input_dialect.wav"
  },
  {
    "id": "dongbei_埋怨",
    "key": "dongbei",
    "name": "东北话 (Northeastern)",
    "lat": 41.8,
    "lng": 123.43,
    "scene": "埋怨",
    "text_std": "你怎么故意把衣服弄脏了？",
    "text_dia": "你怎么成心把衣服整这就埋汰？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/dongbei_埋怨/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/dongbei_埋怨/02_input_dialect.wav"
  },
  {
    "id": "sichuan_疑问",
    "key": "sichuan",
    "name": "四川话 (Sichuanese)",
    "lat": 30.57,
    "lng": 104.06,
    "scene": "疑问",
    "text_std": "你在做什么？",
    "text_dia": "你在搞啥子？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_疑问/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_疑问/02_input_dialect.wav"
  },
  {
    "id": "shanghai_日常问候",
    "key": "shanghai",
    "name": "上海话 (Shanghainese)",
    "lat": 31.23,
    "lng": 121.47,
    "scene": "日常问候",
    "text_std": "你好，你吃饭了吗？",
    "text_dia": "侬好，侬饭吃过伐？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shanghai_日常问候/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shanghai_日常问候/02_input_dialect.wav"
  },
  {
    "id": "cantonese_喜好",
    "key": "cantonese",
    "name": "广东话 (Cantonese)",
    "lat": 23.12,
    "lng": 113.26,
    "scene": "喜好",
    "text_std": "我很喜欢吃这个。",
    "text_dia": "我好钟意食呢个。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/cantonese_喜好/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/cantonese_喜好/02_input_dialect.wav"
  },
  {
    "id": "shan3xi_自我表达与赞美",
    "key": "shan3xi",
    "name": "陕西话 (Shaanxi)",
    "lat": 34.34,
    "lng": 108.93,
    "scene": "自我表达与赞美",
    "text_std": "我今天很高兴，这个非常好。",
    "text_dia": "饿今儿个高兴地很，这个嘹咋咧！",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shan3xi_自我表达与赞美/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/shan3xi_自我表达与赞美/02_input_dialect.wav"
  },
  {
    "id": "dongbei_地点与动作",
    "key": "dongbei",
    "name": "东北话 (Northeastern)",
    "lat": 41.8,
    "lng": 123.43,
    "scene": "地点与动作",
    "text_std": "别在这个地方待着，快点走。",
    "text_dia": "别搁这旮沓待着了，麻溜走。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/dongbei_地点与动作/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/dongbei_地点与动作/02_input_dialect.wav"
  },
  {
    "id": "dongbei_埋怨与动作",
    "key": "dongbei",
    "name": "东北话 (Northeastern)",
    "lat": 41.8,
    "lng": 123.43,
    "scene": "埋怨与动作",
    "text_std": "你怎么故意把衣服弄脏了？别磨蹭了。",
    "text_dia": "你怎么成心把衣服整这就埋汰？别磨叽了。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/dongbei_埋怨与动作/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/dongbei_埋怨与动作/02_input_dialect.wav"
  },
  {
    "id": "sichuan_寻找物品",
    "key": "sichuan",
    "name": "四川话 (Sichuanese)",
    "lat": 30.57,
    "lng": 104.06,
    "scene": "寻找物品",
    "text_std": "我的鞋子去哪里了？",
    "text_dia": "我的孩儿跑哪切了？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_寻找物品/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/sichuan_寻找物品/02_input_dialect.wav"
  },
  {
    "id": "tianjin_形容程度",
    "key": "tianjin",
    "name": "天津话 (Tianjin)",
    "lat": 39.08,
    "lng": 117.2,
    "scene": "形容程度",
    "text_std": "那个相声特别有趣。",
    "text_dia": "那个相声倍儿哏儿。",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/tianjin_形容程度/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/tianjin_形容程度/02_input_dialect.wav"
  },
  {
    "id": "cantonese_询问地点",
    "key": "cantonese",
    "name": "广东话 (Cantonese)",
    "lat": 23.12,
    "lng": 113.26,
    "scene": "询问地点",
    "text_std": "请问厕所在哪里？",
    "text_dia": "唔该，厕所喺边度？",
    "audio_std": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/cantonese_询问地点/01_input_standard.wav",
    "audio_dia": "https://huggingface.co/datasets/youngseng/PolySpeech-100-v1/resolve/main/demo-asset/asset2/comparison_output/cantonese_询问地点/02_input_dialect.wav"
  }
];